name: Check workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
          bash miniconda.sh -b -p $HOME/miniconda
          export PATH="$HOME/miniconda/bin:$PATH"
          hash -r
          conda config --set always_yes yes --set changeps1 no
          conda update -q conda
          conda info -a
          conda config --add channels defaults
          conda config --add channels conda-forge
          conda config --add channels bioconda
          conda create -q -n snakemake snakemake python=3.8
      - name: Test
        run: |
          source activate snakemake
          snakemake -j 1 --configfile config.yml
