# Additional sequences requires for cloning in NEB EnGen kit
# https://www.neb.com/protocols/2016/05/11/engen-sqrna-synthesis-kit-s-pyogenes-protocol-e3322
T7_PROMOTER: "TTCTAATACGACTCACTATA" 
THREE_PRIME_OVERLAP: "GTTTTAGAGCTAGA"

GUIDES_PER_CONSTRUCT: 5  # number of gRNA oligos to select per construct.
MAX_DIST_FROM_START: 1000  # Distance from the start of the construct sequence
                           # to the furthest gRNA start. This defines the window
                           # that gRNAs will be selected from. The workflow
                           # will attempt to evenly distribute rRNAs within
                           # this window. 

MIN_DIST: 100  # min distance from start of seq to select targets
MAX_DIST: 1000  # max distance from start of seq to select targets
NUM_TARGETS: 5  # number of targets to select
TARGET_STRAND: "FWD"  # Strand that should be nicked
NICKED_STRAND_IS_TARGET: False  # Set to true of the Cas9 being used nicks the
                                # target strand, set to false otherwise.

SERIES_NAME: "T7_initiation_series"  # TODO: Make so don't need these
SERIES_PREFIX: "T7_init_VR"

PLASMID_MAP_RENAME_SCHEME: "label-scheme.yml"  # Defines the labels and colors
                                               # that will be used for features
                                               # when drawing plasmids maps.
                                               # This is needed because we do
                                               # not want to draw all features
                                               # in the base genbank files and
                                               # some features have long
                                               # ugly names that make plasmid
                                               # maps hard to read.