__default__:
  partition: "high"
  nodes: 1
  cpus: "{threads}"
  name: "{rule}.{wildcards}"
  output: "logs/{rule}.{wildcards}.out"
  time: "00:35:00"
  email: 'etholleman@ucdavis.edu'
  mem: "8000"
